language: python
branches:
  only:
  - master
  - dev
python:
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q pyecharts==0.4.2
script:
  make test