language: python
branches:
  only:
  - master
  - dev
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
install:
  - pip install -r requirements/dev.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q pyecharts==0.4.1
  - python setup.py install
script:
  - nosetests tests
  - python example/manage.py test --noinput
  - flake8 django_echarts tests example --ignore=E501 --max-complexity 10