language: python
branches:
  only:
  - master
  - dev
python:
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q pyecharts==0.4.1
before_script: "flake8 --ignore=E501 --max-complexity 10"
script:
  - nosetests tests
  - PYTHONPATH=. python example/manage.py test --noinput